canonical/landscape-client

.travis.yml
Makefile
landscape/broker/client.py
landscape/broker/tests/test_client.py
landscape/manager/scriptexecution.py
landscape/manager/tests/test_customgraph.py
landscape/manager/tests/test_scriptexecution.py
landscape/package/tests/test_facade.py

A few commits back we skipped a few tests to get CI passing.  This patch fixes those tests so that they pass now.

Un-skip and fix the temporarily skipped tests.

---

.travis.yml
Makefile
Makefile.packaging
Makefile.travis

try using apt to make build work on travis/trusty

try fixing travis build with apt

---

setup_lib.py

Add some subpackages which were not explicitely pulled in pacakging.

add missing subpackages to landscape.lib

---

man/landscape-sysinfo.1
man/landscape-sysinfo.txt

Which plugins are used by default is explained elsewhere, no need to get into details here.

Which plugins are used by default is explained elsewhere

---

landscape/lib/vm_info.py

Request to add the Nutanix sys_vendor to the matching list in vm_info.py

Update vm_info.py to include Nutanix hypervisor

---

landscape/lib/network.py

The error occurs on WSL (1) and causes an error showing up in MOTD.
LP: #1855522

Handle EINVAL error of SIOCETHTOOL ioctl

---

landscape/client/monitor/computertags.py
landscape/client/monitor/config.py
landscape/client/monitor/tests/test_computertags.py

Launchpad is here https://bugs.launchpad.net/landscape-client/+bug/1940786

Computer tags message plugin

---

landscape/client/broker/exchange.py
landscape/client/broker/tests/test_exchange.py
landscape/lib/backoff.py
landscape/lib/tests/test_backoff.py

The original bug is here https://bugs.launchpad.net/landscape-client/+bug/1947399

Broker back off when receiving 5xx responses LP: #1947399

---

landscape/lib/tests/test_vm_info.py
landscape/lib/vm_info.py

https://bugs.launchpad.net/landscape-client/+bug/1827909
https://bugs.launchpad.net/landscape-client/+bug/1971733

Added detection of Parallels to vm_info (LP: #1827909)

---

landscape/lib/config.py
landscape/lib/tests/test_config.py

It took me a while to discover that I had a duplicate entry in my configuration. With this small improvement, people will be pointed in the right direction.

More verbose error

---

landscape/lib/apt/package/store.py

This solution also resolves the exception produced by:
https://bugs.launchpad.net/landscape-client/+bug/1994951

Removed unnecesary select to the database (LP: #1994951)

---

landscape/sysinfo/deployment.py
landscape/sysinfo/tests/test_deployment.py

These are the corrections to #84 which has been around for almost three years

Add landscape-sysinfo CLI arg to specify maximum column width

---

landscape/lib/disk.py

This resolves the bug reported at:
https://bugs.launchpad.net/landscape-client/+bug/1499104

Add zfs and btrfs to stable fs-lists (LP: #1499104)

---

.gitignore
Makefile
snap/snapcraft.yaml

Made some small changes to address feedback from Colin

Cleanup based on feedback from Colin

---

landscape/client/monitor/swiftusage.py

Traceback is this one:
```
Aug 10 08:50:31 T14 landscape-client[4152]: 2023-08-10 08:50:31,417 WARNING  [MainThread] landscape-monitor failed to respond to a ping.
Aug 10 08:50:31 T14 landscape-client[4152]: Traceback (most recent call last):
Aug 10 08:50:31 T14 landscape-client[4152]:   File "/usr/bin/landscape-monitor", line 10, in <module>
Aug 10 08:50:31 T14 landscape-client[4152]:     run(sys.argv)
Aug 10 08:50:31 T14 landscape-client[4152]:   File "/usr/lib/python3/dist-packages/landscape/client/monitor/service.py", line 91, in run
Aug 10 08:50:31 T14 landscape-client[4152]:     run_landscape_service(MonitorConfiguration, MonitorService, args)
Aug 10 08:50:31 T14 landscape-client[4152]:   File "/usr/lib/python3/dist-packages/landscape/client/service.py", line 84, in …
```

Fix error in swift plugin

---

snap/snapcraft.yaml

To test:
1. make sure there are no changes in your checkout of this repo (i.e., `git commit` exits with a non-zero exit code)
2. `snapcraft` should succeed.

fix git commit step of dev snap build in snapcraft.yaml

---

landscape/client/monitor/computerinfo.py
landscape/client/package/releaseupgrader.py
landscape/client/package/taskhandler.py
landscape/client/package/tests/test_reporter.py
landscape/lib/os_release.py

Added path for os-release inside a snap.
Created get_os_filename helper function for fallback logic Updated unit tests

LNDENG-638 fix.

---

.github/workflows/static-analysis.yml

You can view a successful run here: https://github.com/wck0/landscape-client/actions/runs/11977115496

fix: TiOBE TiCS workflow

---

landscape/sysinfo/landscapelink.py
landscape/sysinfo/tests/test_landscapelink.py

edited string for motd to point to right link

fix: Updated motd

---

.github/workflows/ci.yml

See here for details: https://github.com/canonical/landscape-client/actions/runs/14522619906/job/40746882257?pr=314
https://github.com/actions/runner-images/issues/11101

ci: remove unsupported os

---

.flake8
landscape/client/manager/tests/test_ubuntuproinfo.py
landscape/client/manager/ubuntuproinfo.py

Test cases should cover testing

refactor: change ubuntu pro info to use `uaclient.status` instead of subprocess
