- debian/control
(fixed https://bugs.launchpad.net/landscape-client/+bug/1686532)
Without this change, upgrading from earlier versions won't work.
> Constrain the landscape-common version.

- .gitignore
- landscape/message_schemas/server_bound.py
- landscape/package/facade.py
- landscape/package/reporter.py
- landscape/package/store.py
- landscape/package/tests/test_facade.py
- landscape/package/tests/test_reporter.py
- landscape/package/tests/test_store.py
This changes adds client bits to report autoremovable packages back to landscape-server so it can act on them. lp:1208393
Testing: 
sudo apt-get install sl && sudo apt-mark auto sl && apt-get autoremove --dry-run
sudo ./scripts/landscape-client -c root-client.conf
accept in landscape, wait forever for package data to sync or not (server doesn't know about that field)
/tmp/landscape-root/package-reporter.log should queue autoremovable once (those are diffs)
grep autoremovable /tmp/landscape-root/broker.log # shows package report being sent even if currently ignored by servers
> Autoremove reporting

- landscape/configuration.py
- landscape/tests/test_configuration.py
Handle SystemExit exception, as those don't propagate past the reactor.
This will avoid hanging forever in environements (installer-chroot) where the broker will not start.
To test: ln -s /bin/echo /etc/init.d/landscape-client && sudo ./scripts/landscape-config --silent
Script should timeout and not run forever.
> Stop reactor in landscape-config on broker error.

- landscape/package/reporter.py
- landscape/package/tests/test_reporter.py
> Check if ubuntu-release-upgrader is running before apt-update.

- landscape/lib/tests/test_vm_info.py
- landscape/lib/vm_info.py
register client.
verify the client is seen as kvm (and uses VM seat).
> Sets vm_info to "kvm" for new AWS EC2 C5 instances which are now based on kvm.

- landscape/lib/tests/test_vm_info.py
- landscape/lib/vm_info.py
Set vm-info to kvm for digitalocean droplets.
> set vm_info to kvm for digitalocean instances

- debian/rules
Fixes  LP: #1737729
I'm a bit wary of "hardcoding" the python version like that, but it seems we are all in with python 3 with this package. I also removed the "-" prefix from the include directory because I want to know if the file isn't there.
> Source python.mk from the correct python versioned directory

- landscape/client/broker/store.py
- landscape/client/broker/tests/test_store.py
* apt-install landscape-client. (py27)
* configure in /etc/landscape/client.conf
* call /usr/bin/landscape-client and wait to be messages pending delivery
* check /var/lib/landscape/client/messages/0 for a couple messages
* run ./script/landscape-broker -c /etc/landscape/client.conf \
-d /var/lib/landscape/client
* Messages get delivered, broker queue gets emptied, no stack trace on client.
* Check on message-server for delivered messages.
> Best-effort decode old py27 message keys.

- landscape/client/deployment.py
- landscape/client/tests/test_deployment.py
Testing:
./scripts/landscape-client
check log names in /tmp/landscape-root
> add missing program_name to log name

- landscape/client/broker/store.py
- landscape/client/broker/tests/test_store.py
- landscape/client/package/reporter.py
- landscape/client/package/tests/test_reporter.py
These exact steps reproduce the initial issue. Any other step has the risk
of server_uuid being seen as changed and properly persisted.
* apt install landscape client (py2.7)
* request registration. stop client.
* accept client
* sudo ./scripts/landscape-client -c /etc/landscape/client.conf
* tail -F /var/log/landscape/package-reporter.log | grep hash-id
Check for 404. If you're using racecar and have no hash-id-db, check
the URL being hit on landscape doesn't contain b"<server_uuid>"
> Decode server uuid pre-py3 upgrade. (LP: #1718696)

- debian/landscape-client.postinst
- landscape/lib/apt/package/facade.py
- landscape/lib/apt/package/tests/test_facade.py
* install landscape-client on artful+ and register
* apply a simple package profile (depends sl)
* notice failure to update packages (Release file not found)
* apt-get build-depends ./ && dpkg-buildpackage -b --us -uc && dpkg -i ../*.deb
* check upgrade added trust option to :
/etc/apt/sources.list.d/_landscape-internal-facad.list[.orig]
* re-check "apt-get update" works
> Implicitly trust file-local sources managed by landscape (LP: #1736576)

- landscape/client/package/reporter.py
- landscape/client/package/taskhandler.py
- landscape/client/package/tests/test_taskhandler.py
Testing:
* install landscape-client on artful/bionic
* kick a package profile (should break because of apt-secure being default in distro, but the task will stay)
* upgrade
* verify package-changer/monitor logs for stack trace
> decode message types in task handler and continue on unknown type

- landscape/client/broker/registration.py
- landscape/client/broker/tests/test_registration.py
- landscape/client/manager/shutdownmanager.py
- landscape/client/manager/tests/test_shutdownmanager.py
* ShutdownManager was erroneously concatenating  bytes as str, unlike
other ProcessProtocol subclasses which appear correct.
* Registration data is stored and fetched as bytes, whereas test code
and callsites assume str, thus breaking exchange comparison of
secure-id when the service restarts during the activity processing.
Although the behaviour is seen during an upgrade, it can easily be triggered
from py3 only.
* Register against landscape
* Request a reboot
* (restart the client after reboot)
* expect the activity to succeed.
> Add decoding to registration and shutdown data.

- .travis.yml
- landscape/lib/tests/test_network.py
This replaces the python test matrix by containerized runs on xenial (py2) and bionic (py3).
Apart from highlighting a small issue with tests (fixed in this branch), it seems containers run slightly
faster than pip dependencies (still used for coverage and lint).
Check the travis status for verification.
> Use lxd containers for CI testing

- debian/landscape-common.postinst
- debian/landscape-common.prerm
Revert the original change for #1621978. The dpkg-divert was in the wrong package (common instead of client), but even so, the mere presence of the client package doesn't mean this system is managed by landscape: the registration should be checked.
> Revert the original change for #1621978

- debian/landscape-client.postinst
Without this check, a fresh install of the package emits this error:
```
Setting up landscape-client (18.01-0ubuntu1) ...
grep: /etc/apt/sources.list.d/_landscape-internal-facade.list: No such file or directory
```
> Check if the file exists before grepping it.

- debian/landscape-common.prerm
It's a leftover from when the dpkg-divert change was reverted in a previous commit.
> Remove unused variable

- debian/changelog
d/changelog update from the bionic upload, and opening up 18.03 development. Doesn't have to be 18.03, but it must be higher than 18.01 because that's in bionic now.
> changelog update

- landscape/lib/tests/test_vm_info.py
- landscape/lib/vm_info.py
Scan sys, bios and chassis DMI to detect hypervisor (LP: #1754073)
```
uvt-simplestreams-libvirt --verbose sync arch~amd64 release~xenial
uvt-kvm create vm
virsh edit vm
<os>
...
<smbios mode='sysinfo'/>
</os>
<sysinfo type="smbios">
<system>
<entry name='manufacturer'>Apache Software Foundation</entry>
<entry name='product'>CloudStack KVM Hypervisor</entry>
</system>
</sysinfo>
<cpu match='exact'> 
<model fallback='allow'>core2duo</model>
<vendor>Intel</vendor>
</cpu>
virsh destroy vm && virsh start vm
uvt-kvm ssh vm --insecure
git clone --single-branch --branch 1754073_extend_kvm_detection https://github.com/simpoir/landscape-client && cd landscape-client
sudo apt-get build-dep ./ && sudo dpkg-buildpackage -b -us -uc
sudo dpkg -i ../landscape-*.deb
sudo apt-get -f …
```
> Extend vm_info detection to other dmi fields.

- landscape/lib/apt/package/facade.py
This should remove the tracebacks under python3 + bionic. (LP: #1758529)
```
edit root-client.conf
sudo ./scripts/landscape-client -r root-client.conf
log to landscape, accept the client, wait for packages to sync.
search for a package (e.g. fortune), mark it for install; wait.
grep pulse /tmp/landscape-root/*.log  # should return nothing
```
> Override the apt progress pulse().

- landscape/client/package/changer.py
- landscape/client/package/tests/test_changer.py
In the case that all tasks have already been performed (e.g. by external processes), return a meaningful message rather than nothing. (LP: #928933)
> Return non-blank message when tasks already performed

- landscape/client/manager/aptsources.py
- landscape/client/manager/tests/test_aptsources.py
Support both unicode and bytes content for apt-sources-replace,
as content should be unicode, but can be passed as bytes after a client
upgrade from python 2.7
* on a bionic container, ./scripts/landscape-client -c root-client.conf
* on the server,
```
make freshdata && ./dev/racecar
source ./dev/setup_api
curl 'https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xC0B21F32' > mirror_key
landscape-api import-gpg-key ubuntu-new-mirror-key ./mirror_key
// the sign-key comes from freshdata
landscape-api create-series --pockets security --components restricted --architectures amd64 --mirror-gpg-key ubuntu-new-mirror-key --gpg-key sign-key --mirror-uri http://archive.ubuntu.com/ubuntu/ --mirror-series bionic bionic-repo ubuntu
landscape-api …
```
> Handle unicode apt-sources-replace (LP: #1771443)

- landscape/client/deployment.py
Twisted default log initialization is to use a 64k lines deque buffer,
each referencing the log_source objects, thus keeping a large amount of
references to twisted objects and keeping them from being collected.
This initializes the twisted logging to drop that buffer. (LP: #1685885)
The leak is not quite noticeable without waiting considerably.
The easiest way is to instrument a few process like the watchdog
(which is a good candidate because it does almost nothing)
in landscape/client/watchdog.py:418 add
+        import objgraph; print(objgraph.show_growth())
and call ./scripts/lanscape-client -c root-client.conf
And watch it level after a few seconds.
Other processes are harder to track as they go up and down considerably.
> Avoid leaking memory through unused twisted logs.

- debian/landscape-sysinfo.wrapper
- landscape/client/deployment.py
- landscape/lib/apt/package/tests/test_facade.py
Avoid encoding errors scanning process (LP: #1780071)
on bionic or later
$ dpkg-buildpackage -b
$ dpkg -i ../landscape-common_18.03-0ubuntu1_amd64.deb
$ sh -c 'sleep 300; echo "ಠ_ಠ"' &
$ sudo login
Should show sysinfo as part of motd without printing the error log message.
> Set LANG in sysinfo wrapper.

- landscape/client/package/releaseupgrader.py
At present, landscape-client fails to report the completion (or failure) of a release upgrade from trusty to xenial due to the delayed import of twisted.internet.unix (part of LP: #1670291).
* Create a trusty container
* Patch the landscape client in the container
* Register it with landscape (either hosted or a test instance should do)
* Request a release upgrade (implicitly to xenial) of the client from landscape
* Ensure the result of the release upgrade is reported (success or failure) in landscape
> Enable landscape-client to survive trusty upgrade

- landscape/client/manager/shutdownmanager.py
- landscape/client/manager/tests/test_shutdownmanager.py
Add an additional step when shutdown fails to power-off or restart the machine; call the /sbin/poweroff or /sbin/reboot binaries instead to attempt an immediate shutdown. We can't (reliably) report success or failure from this, so the operation will still appear failed but it appears more reliable practice runs with VMs and containers in post-trusty upgrade environments. (LP: #1670291)
* Launch a trusty VM and/or container
* Patch landscape-client in the instance
* Register with landscape
* Request an upgrade to xenial
* Upgrade should complete successfully; don't reboot the instance yet!
* Re-patch the landscape-client (because the release-upgrade will have over-written the prior patch) and restart the landscape-client
* Request a restart of the machine from within landscape
* Restart …
> Reboot means reboot! (LP: #1670291)

- landscape/client/package/reporter.py
- landscape/client/package/tests/test_reporter.py
This should avoid loop when inconsistencies are present in the database
through either corruption or server-restore. (LP: #1616116)
* launch a landscape server and register (using ppa packages is somewhat simpler as hash-db is pre-populated).
* register client against server. wait for package info
* pg_dumpall
* add a repo and wait for new package to show on client.
* restore postgres backup.
* trigger a package install from the new repo to have new package show up
* if you haven't regenerated hash-ids on the server, clients will be stuck in a loop. this is to be expected as the server is inconsistent with itself.
* client should resync once then will re-fetch hash on the next run. Some hash-id requests may go through in the meantime.
> Clear hash id database on package resync.

- Makefile.travis
- landscape/client/package/reporter.py
- landscape/client/package/tests/test_reporter.py
- landscape/lib/apt/package/store.py
- landscape/message_schemas/server_bound.py
sudo ./scripts/landscape-client -c path_to_your_favorite_config
Check the debug logs for packages ids being reported. in addition to available,
there should be a couple of security.
> report packages from security-pocket

- Makefile
- landscape/client/broker/tests/test_store.py
- landscape/client/monitor/processorinfo.py
- landscape/client/monitor/tests/test_computerinfo.py
- landscape/client/package/releaseupgrader.py
- landscape/client/package/reporter.py
- landscape/lib/fs.py
- landscape/lib/persist.py
- landscape/lib/tag.py
- landscape/lib/tests/test_fs.py
- landscape/lib/vm_info.py
And while we're at it, clean up some of the mess in fs.py: there's
almost no circumstances where we want landscape client to fall over
because a text file has invalid UTF-8 (the original function before the
py2/3 split had no such circumstances that'd lead to decoding errors).
Furthermore, read_binary_file's limit was wrong when positive (not that
anything called it with a positive limit) and read_text_file defeated
the purpose of having a limit by permitting an arbitrarily large read
even when one was set.
> Allow bad chars in system vendor files (LP: #1799843)

- landscape/lib/network.py
- landscape/lib/tests/test_network.py
- landscape/sysinfo/network.py
- landscape/sysinfo/sysinfo.py
- landscape/sysinfo/tests/test_network.py
- landscape/sysinfo/tests/test_sysinfo.py
Prerequisite of [LP: #829379](https://bugs.launchpad.net/landscape-client/+bug/829379).
Sample output:
```
$ ./scripts/landscape-sysinfo
System load:    2.32      Users logged in:       1
Usage of /home: unknown   IPv4 address for eth0: 10.51.30.224
Memory usage:   1%        IPv4 address for eth0: 172.16.102.1
Swap usage:     0%        IPv4 address for eth1: 172.16.103.3
Processes:      39        IPv4 address for eth1: 172.16.104.4
```
Depends on https://github.com/CanonicalLtd/landscape-client/pull/59.
> Sysinfo: add support for multiple IPv4 addresses per interface

- landscape/lib/network.py
- landscape/lib/tests/test_network.py
- landscape/sysinfo/network.py
- landscape/sysinfo/tests/test_network.py
Fixes [LP: #829379](https://bugs.launchpad.net/landscape-client/+bug/829379).
Sample output:
```
$ ./scripts/landscape-sysinfo
System load:     1.67      IPv4 address for eth0: 10.51.30.224
Usage of /home:  unknown   IPv6 address for eth0: 2001::1
Memory usage:    1%        IPv6 address for eth0: 2001:470:28:5b2::1
Swap usage:      1%        IPv4 address for eth1: 172.16.103.3
Processes:       35        IPv4 address for eth1: 172.16.104.4
Users logged in: 1         IPv6 address for eth2: 2::1
```
Depends on https://github.com/CanonicalLtd/landscape-client/pull/61.
>  Sysinfo: add support for multiple IPv6 addresses per interface (LP: #829379)

- landscape/lib/network.py
- landscape/lib/tests/test_network.py
- Ignore network interfaces that are not UP.
- Prevent crash on IPv4 network interface with no mac address (e.g. VPN `tun0`).
- Prevent crash on IPv4 network interface with no netmask (haven't really seen it IRL, but let's be defensive).
> Networking fixes

- debian/landscape-client.postinst
Normally we set this in the default config, but older clients did not require
it at install and all clients run fine without it being explicitly set in the
config. Therefore this make the config line optional again.
dpkg-buildpackage -b
dpkg -i ../*.deb
sed -e /data_path/d -i /etc/landscape/client.conf<Paste>
dpkg -i ../*.deb
> Set default value if data_path is missing. (LP: #1728681)

- debian/control
- landscape/lib/apt/package/facade.py
- landscape/lib/apt/package/testing.py
- landscape/lib/apt/package/tests/test_facade.py
This should resolve some obvious regressions  with python-apt 1.9 on both eoan and focal when trying to apply package profiles.
* added net-tools to build-deps, as it's not longer pre-seeded
* apt_pkg.rewrite_section by TagSection.write
* try call on removed fixer.install_protect() as it was deemed a NOOP in current version.
There is an additional test (test_change_package_holds) which still regresses. I've yet to determine the impact, but that will be addressed in a separate change.
> Replace removed calls from python-apt 1.9 (LP: #1850205)

- .travis.yml
- landscape/client/package/tests/test_changer.py
- landscape/lib/apt/package/testing.py
This should enable tests to pass on disco+, avoiding changing package IDs due:
* to an unsorted Packages file
* to package conflict with universe "bar" package
Also enable focal testing in travis, since they now pass.
> Rename test held package to avoid conflicts

- landscape/lib/disk.py
File system types of `/home` and `/` on WSL are `drvfs` and `lxfs`.
So I just added these two fs-types to the "stable" fs-lists.
And now it can display the usage correctly :)
> Fix 'usage of /home: unknown' on WSL

- landscape/client/broker/tests/test_transport.py
- landscape/client/package/reporter.py
- landscape/client/package/tests/test_reporter.py
- landscape/lib/apt/package/tests/test_skeleton.py
This is a workaround for (LP: #1827857), where python3-apt incorrectly
assumes the encoding.
> Override encoding in package-reporter.

- landscape/client/lockfile.py
- landscape/client/reactor.py
- landscape/client/tests/test_amp.py
- landscape/client/tests/test_lockfile.py
This change tries to clean up stale lock files, which points to dead processes. (LP: #1870087)
install/register client.
```
```
your fake locks should have been replaced by and point to valid PIDs (not 1).
You might as well check that lock conflicts do conflict while services are running:
```
twisted.internet.error.CannotListenError: Couldn't listen on any:b'/var/lib/landscape/client/sockets/broker.sock
```
> Clean up stale lock files

- debian/landscape-client.service
This keeps dpkg from killing itself through the whole cgroup when
landscape self-upgrades.
> Set killmode on service.

- example.conf
- landscape/client/manager/config.py
- landscape/client/manager/scriptexecution.py
- landscape/client/manager/tests/test_scriptexecution.py
Client side setting to make the script output size configurable.
This was hardcoded to 50000 (now 512kB default)
> Add new optional config option script_output_limit

- .travis.yml
- landscape/client/broker/tests/test_store.py
- landscape/lib/apt/package/facade.py
- landscape/lib/apt/package/tests/test_facade.py
This should address issues with package not autoremoved. (LP: #1878957)
In a new container
1. sudo ./scripts/landscape-client -c root-client.conf
2. wait for packages to synchronize to landscape-server
3. trigger an install of something new (e.g. sl)
4. trigger an upgrade/downgrade of something marked auto (e.g. tzdata)
5. trigger an upgrade/downgrade of something manual (e.g. bash)
6. check only the updated auto package is marked auto
```
$ apt-mark showmanual sl
sl
$ apt-mark showauto tzdata
tzdata
$ apt-mark showmanual bash
bash
```
> Preserve auto flag on package changer operations.

- landscape/client/broker/exchange.py
- landscape/client/broker/registration.py
- landscape/client/broker/tests/test_registration.py
Fix a py3 regression where registration error codes are not passed to the landscape-config tool but instead gets a timeout.
Testing:
```
$ dpkg-buildpackage -b && sudo dpkg -i ../landscape-c*.deb
$ sudo landscape-config
$ sudo landscape-config --account-name invalid --silent --computer-title foo
Please wait...
Invalid account name or registration key.
$ sudo landscape-config --account-name standalone --silent --computer-title foo
Please wait...
('Maximum number of computers pending approval reached. ', 'Login to your Landscape server account page to manage pending computer approvals.')
```
> decode registration error codes as str

- landscape/client/broker/service.py
- landscape/client/manager/service.py
- landscape/client/monitor/service.py
This should allow services to let their publisher shut down and clean
after itself, thus avoiding stale locks and sockets. (LP: #1870087)
Spawn and stop the client. There should not be any lock or socket left.
```
sudo ./scripts/landscape-client -c root-client.conf
<ctrl-c>
ls -la /tmp/landscape-root/sockets/
<empty listing>
```
> Return missing deferred on service shutdown.

- landscape/lib/gpg.py
- landscape/lib/tests/test_gpg.py
This fixes a regression of bionic to focal upgrade. (lp:1903776)
* sudo apt build-dep . && dpkg-buildpackage -b
* install resulting packages inside a bionic container.
* register against landscape.c.c
* under Computers -> Packages, trigger a release upgrade (last link)
* Wait for activity success. Check `/var/log/landscape/release-upgrader.log`
> Scan /etc/apt/trusted.gpg.d when verifying release upgrade.

- landscape/lib/network.py
On booting a fresh hirsute daily image on a Raspberry Pi, the following appears in the MOTD:
```
=> There were exceptions while processing one or more plugins. See
/var/log/landscape/sysinfo.log for more information.
```
The log mentioned contains the following:
```
2021-02-19 15:27:28,062 ERROR    Network plugin raised an exception.
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/landscape/sysinfo/sysinfo.py", line 99, in run
result = plugin.run()
File "/usr/lib/python3/dist-packages/landscape/sysinfo/network.py", line 36, in run
device_info = self._get_device_info()
File "/usr/lib/python3/dist-packages/landscape/lib/network.py", line 163, in get_active_device_info
speed, duplex = get_network_interface_speed(
File …
```
> Replace deprecated tostring() call with tobytes()

- landscape/client/broker/server.py
- landscape/client/broker/tests/test_server.py
This should address issues with upgrades never reporting back
when migrating to python3 while still having py27 processes. (LP: #1943291)
The quick and easy way to verify this is to
- apply [this patch](https://pastebin.ubuntu.com/p/YTbYjFrvNn/)
- edit `root-client.conf` to point to your preferred server
- then call `sudo ./scripts/landscape-client -c root-client.conf`
- then trigger a release upgrade (in the UI computer packages page, bottom-most link "release upgrade")
- and wait a few minutes for the NOOP update to succeed
The alternative would be to build the client package, create a local repo, and uncomment the extra source during the upgrade.
> Translate legacy py27 messages to py3 messages in broker server.

- landscape/lib/network.py
- landscape/lib/tests/test_network.py
From here https://bugs.launchpad.net/landscape-client/+bug/1950311
> Fix slow sysinfo when large number of interfaces present #1950311

- landscape/client/broker/exchange.py
- landscape/client/broker/tests/helpers.py
- landscape/client/broker/tests/test_exchange.py
- landscape/lib/message.py
From here https://bugs.launchpad.net/landscape-client/+bug/1917540
> Empty exchanges after sequence number jumping LP: #1917540

- landscape/client/broker/exchange.py
- landscape/client/broker/server.py
- landscape/client/broker/tests/test_registration.py
- landscape/client/broker/transport.py
- landscape/client/manager/keystonetoken.py
- landscape/client/user/provider.py
- landscape/lib/apt/package/skeleton.py
- landscape/lib/base64.py
- landscape/lib/bpickle.py
- landscape/lib/compat.py
- landscape/lib/disk.py
- landscape/lib/network.py
- landscape/lib/testing.py
- landscape/lib/user.py
* replace deprecated twisted _PY3
* replace legacy types which are gone (unicode, long)
For the bug itself, running `./scripts/landscape-sysinfo` from within a
jammy container should be sufficient.
Since this branch touches practically every code path, I would recommend
fully launching the client and registering it.
> Fixes import issues with jammy. (LP: #1962539)

- debian/landscape-client.logrotate
Use systemctl to signal parent process instead of using pidfile (LP: #1968189)
Only signal once for all rotations.
```
apt-get build-dep .
dpkg-buildpackage -b
dpkg -i ../landscape*.deb
systemctl start landscape-client  # it's unconfigured, but this is fine.
tail -F /var/log/landscape/*.log &
logrotate --force /etc/logrotate.conf  
```
You'll get a  couple of outputs, one per landscape process log, telling the log files were rotated.
> Use systemctl to signal post-logrotate.

- debian/rules
The client package using no-start (due to being enabled from
landscape-config), avoid stopping the service on upgrade so that
1. landscape may upgrade itself and see the upgrade complete
2. the client doesn't stay down after upgrade (due to no-start, dh will never restart it)
> Disable stopping service during upgrade.

- landscape/client/monitor/processorinfo.py
This adds support so that the landscape client can successfully run on a riscv processor.  it was tested on a VisionFive v1 board against the beta Landscape client.
> Added initial support for risc-v processor family

- landscape/client/package/releaseupgrader.py
- landscape/client/package/tests/test_taskhandler.py
- landscape/lib/lsb_release.py
- landscape/lib/tests/test_lsb_release.py
As requested in Bug #1990268 here is some code that should replace the /etc/lsb-release dependency (which is Ubuntu-specific) with more generic /usr/bin/lsb_release dependency, allowing package reporting to work on Debian.
Looking through the code there are various references in the tests - I'm afraid this is beyond my skills, but hoping someone with more knowledge might be able to help out here!
> Replace dependency on /etc/lsb-release with /usr/bin/lsb_release to permit Debian compatibility - #1990268

- landscape/sysinfo/load.py
More recent kernels (e.g. 5.15 in Ubuntu 22) seem to give many more than the 2 digits of precision that older ones (e.g. 5.4 in Ubuntu 20) gave in the return from getloadavg().
This restores the backwards compatibility and prevents silly things like this from landscape-sysinfo:
System load: 0.080078125   Processes: 124
> Round load average to 2 decimal places

- debian/landscape-client.postrm
- landscape/client/manager/aptsources.py
- landscape/client/manager/tests/test_aptsources.py
- landscape/lib/apt/package/facade.py
Manual testing instructions:
1) Register client to on prem server
2) Follow steps to set up mirror (use restricted component to limit file size) all the way to "Associate computers with repository profile" making sure to associate the profile with the registered client https://docs.ubuntu.com/landscape/en/repositories
3) Look in /etc/apt/trusted.gpg.d for the keys and confirm no 'trusted.gpg' file gets created
> Remove deprecated apt-key to stop gpg warning (LP: #1973202)

- landscape/lib/schema.py
This patch separates the coercion of bytes-type schema data in py2 from py3. The py2 behaviour keeps the previous behaviour of raising an exception if the data is not bytes, but the py3 behavious will encode the data as bytes if it is a py3 unicode str.
> Separate bytes-handling for python2 and python3

- landscape/lib/apt/package/testing.py
- landscape/lib/apt/package/tests/test_skeleton.py
This is a test to reproduce the bug reported at [LP: #1813442](https://bugs.launchpad.net/landscape-client/+bug/1813442) :
```
landscape.lib.apt.package.tests.test_skeleton
SkeletonAptTest
test_build_skeleton_broken_description ...                          [ERROR]
===============================================================================
[ERROR]
Traceback (most recent call last):
File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
yield
File "/usr/lib/python3.10/unittest/case.py", line 591, in run
self._callTestMethod(testMethod)
File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
method()
File ".../landscape-client/landscape/lib/apt/package/tests/test_skeleton.py", line 340, in test_build_skeleton_broken_description
skeleton = …
```
> Test for broken control file (LP: #1813442)

- example.conf
- landscape/client/monitor/config.py
- landscape/client/monitor/tests/test_ubuntuprorebootrequired.py
- landscape/client/monitor/ubuntuprorebootrequired.py
- landscape/message_schemas/server_bound.py
- Adds a monitor plugin to check if a reboot is required
- Update documentation on available plugins
> send ubuntu pro reboot output

- landscape/client/deployment.py
- landscape/client/manager/aptsources.py
- landscape/client/tests/test_deployment.py
There's some really weird interactions going on with the default CLI param value and the value in the config file. To reduce the impact, I've decided that this config will be only in the conf file until we upgrade our configparser and argparser issues.
> make manage_sources_list_d conf-file-only

- landscape/lib/apt/package/facade.py
- landscape/lib/apt/package/skeleton.py
- landscape/lib/apt/package/tests/test_skeleton.py
I got deeper into this problem and found that it was happening because we were using "version.record" which is the source of the failure.
Since we don't want to mess up with the UnicodeDecodeError still happening in the apt package, I  decided to switch the way the dependencies information is readen from the package, and I removed "version.record" from the code so it doesn't try to parse the broken data anymore.
Also, I discovered in the original source code that "PreDepends" was empty in all my tests. Now it has information as I think it should work. I would like somebody to check my solution in search of some collateral problems with the new "PreDepends".
I also renamed a variable "hash" in facade to "hash_skeleton".
> Changed the way Dependency data is readen (LP: #1813442)

- landscape/client/broker/store.py
- landscape/client/broker/tests/test_store.py
Manual testing instructions:
1. Modify `directory_size` to be 10 instead of 1000 in the class `__init__` of `store.py`
1. Change the "Sending payload" and "Received payload" to not print the payload in client/broker/transport.py. This makes reading the output logs easier (optional)
1.  Connect this client to a server and accept the computer
1. Either stop the server or stop client to make the message system unreachable (change message system config `url` to be something that doesn't exist. Just changing the url suffix should be sufficient)
1. Start client and take a look at the `messages` directory which is inside of the `data-path` config and watch the directory grow (should not take long).  Once there are 4 folders in there observer the 5th one to get deleted (max_dirs is 4).  Note …
> Limit message data directory size

- landscape/client/configuration.py
- landscape/client/tests/test_configuration.py
- landscape/lib/config.py
See https://bugs.launchpad.net/landscape-client/+bug/2028516 for background:
> There's actually no good reason not to accept valid utf-8 as the computer-title. Our message schema declares the title as unicode, and it is stored on the server side as unicode.
> This bug exists because when we write the provided config to /etc/landscape/client.conf we assume the encoding of that file is ASCII. We shouldn't need to make this assumption, and should instead enforce ASCII-ness on a per-field basis (as we do for other types, such as fields that must be integers, etc).
> use utf-8 for client config file

- debian/landscape-client.service
- debian/rules
This re-resolves https://bugs.launchpad.net/ubuntu/+source/landscape-client/+bug/2027613 - see the discussion there regarding the rationale behind this change.
> use --is-registered as systemd service start condition

- landscape/client/broker/ping.py
- landscape/client/broker/tests/test_ping.py
To test:
1. Run landscape server using a self-signed certificate (landscape-scalable charm bundle should give you this by default)
2. Make sure `ping_url` is `https`
3. Run client with `--ssl-public-key=<PATH_TO_PUB_KEY.crt>` or set `ssl_public_key = <PATH_TO_PUB_KEY.crt>` in your .conf
4. Register your client and make sure it can ping. Easiest way to check is to `tail -f /var/log/haproxy.log | grep ping` on your haproxy unit in the juju model. Make sure the traffic is on port `443`.
If you're having trouble getting the cert from your server to your client, a quick way is:
```
echo -n | openssl s_client -connect <HAPROXY_URL>:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee /etc/landscape/server.crt
```
Please also make sure this doesn't break plain HTTP pings.
> pass ssl_public_key settings into pinger to support self-signed cert TLS

- snap/snapcraft.yaml
prior to this change builds would only happen on amd64. Here's proof that with this change it builds for all listed arches: https://launchpad.net/~mitchburton/+snap/snapcraft-landscape-client-b8bc866f93dd763be09f288a7a444fec
> fix format of architectures in snapcraft.yaml so launchpad likes it

- README
- example.conf
- landscape/__init__.py
- landscape/client/broker/config.py
- landscape/client/broker/registration.py
- landscape/client/broker/store.py
- landscape/client/broker/tests/test_config.py
- landscape/client/broker/tests/test_exchange.py
- landscape/client/broker/tests/test_registration.py
- landscape/client/broker/tests/test_store.py
- landscape/client/configuration.py
- landscape/message_schemas/server_bound.py
Manual Testing Instructions:
1. Get this PR code.
2. Setup a development `landscape-server` instance.
3. Install this code to the instance running server: `./build/venv/bin/pip install "git+https://github.com/wck0/landscape-client.git"`
4. Run the server code.
5. Edit the `landscape-client.conf` file for `landscape-client` to point to your dev server.
6. Add a new line to that same file: `hostagent_uid = some test value`
7. Run the development client: `sudo ./scripts/landscape-client`
8. Wait for it to register with your dev server.
9. Watch the logs or check in `/tmp/landscape/broker.log` that the registration message includes the `hostagent_uid` key with the value you set above and that it is using version 3.4 of the message schema.
10. Verify you can accept the computer as usual.
> Add optional hostagent_uid field to the message schema.

- README
- snap/snapcraft.yaml
When trying to run `make snap-debug`, the following error occurs:
> :: copying landscape/client/package/taskhandler.py -> /root/parts/landscape-client/build/landscape-client-0.0.1/.pybuild/cpython3_3.10/build/landscape/client/package
> **_:: error: package directory 'landscape/client/snap_http' does not exist_**
> :: E: pybuild pybuild:369: build: plugin distutils failed with: exit code=1: /usr/bin/python3 setup.py build
> :: dh_auto_build: error: pybuild --build -i python{version} -p 3.10 returned exit code 13
`landscape/client/snap_http` is a symlink to `snap-http/snap_http`. Currently, `snap-http` isn't being copied which means the symlink is not resolved, hence the _"package directory 'landscape/client/snap_http' does not exist"_ error. This change ensures that the `snap-http` …
> fix: copy submodules when building the snap

- landscape/client/monitor/tests/test_temperature.py
- landscape/lib/sysstats.py
- landscape/lib/tests/test_sysstats.py
- landscape/sysinfo/tests/test_temperature.py
On most systems `hwmon` provides access to the temperature information on more devices, including the CPU and GPU on most systems. These additional temperature sources yield a more accurate maximum temperature for the overall system.
With this change, the following precedence is used for reading thermal zones (depending on availability):
1. `/sys/class/hwmon/*/temp*_input`
2. `/sys/class/thermal/*/temp`
3. `/proc/acpi/thermal_zone/*/temperature`
> Read temperature from hwmon devices

- landscape/client/monitor/computerinfo.py
- landscape/client/monitor/tests/test_computerinfo.py
- landscape/client/snap_utils.py
- landscape/client/tests/test_snap_utils.py
- landscape/message_schemas/server_bound.py
- setup_client.py
depends on https://github.com/Perfect5th/snap-http/pull/6
> Add snapd device information to ComputerInfo message

- landscape/client/deployment.py
- landscape/client/monitor/computerinfo.py
- landscape/client/monitor/tests/test_computerinfo.py
- landscape/client/snap_utils.py
- landscape/client/tests/test_deployment.py
- landscape/client/tests/test_watchdog.py
- landscape/client/watchdog.py
- landscape/lib/format.py
- landscape/lib/tests/test_format.py
- snap/hooks/install
If auto-registration is enabled & the auto-registration process has not already run, the client will attempt to generate a computer title based on `computer-title-pattern` (see the L017 spec.). If other configuration is ok (API URLs, account name, etc), the client will contact the landscape server and automatically request registration within ~5 minutes. 
Sample registration request with `computer-title-pattern="${model:8:7}-${serial:0:8}"`:
> add: computer title generation for zero-touch deployment

- landscape/client/manager/snapmanager.py
- landscape/client/manager/tests/test_snapmanager.py
- landscape/client/monitor/snapmonitor.py
- landscape/client/monitor/tests/test_snapmonitor.py
These changes were missed during the migration to the `snap-http` library.
> fix running tasks on the snap manager

- landscape/client/manager/tests/test_usermanager.py
- landscape/client/manager/usermanager.py
- landscape/client/monitor/tests/test_usermonitor.py
- landscape/client/monitor/usermonitor.py
- landscape/client/user/management.py
- landscape/client/user/tests/helpers.py
- landscape/client/user/tests/test_management.py
This change allows us to list, add, and remove SSO users on Ubuntu Core systems.
Example listing on staging:
Depends on https://github.com/Perfect5th/snap-http/pull/7
> add: user management on Core

- landscape/lib/bpickle.py
- landscape/lib/tests/test_bpickle.py
bpickle has a bug: if you ask it to `loads` a dict, list, or tuple containing a string or bytestring with a negative length, it can enter an infinite loop as it steps back and scans the same section of the string repeatedly.
Fairly minimal reproduction:
```python
from landscape.lib import bpickle
bpickle.loads(b'lu-4test;')
```
This appears to never return.
Fix is to guard against negative length values. Zero values are okay, as you already get a different error for those, though it could perhaps be clearer.
> bpickle: guard against negative string/bytestring lengths

- landscape/client/manager/snapmanager.py
- landscape/client/manager/tests/test_snapmanager.py
- landscape/client/monitor/snapmonitor.py
- landscape/client/monitor/tests/test_snapmonitor.py
- landscape/message_schemas/server_bound.py
In addition to the running processes, we should send the running snap services to the Landscape server. This will then permit the display of these services along with the option to trigger start/stop/restart commands.
> add: snap services management

- landscape/client/manager/snapmanager.py
- landscape/client/snap_utils.py
- landscape/client/user/management.py
- landscape/client/user/tests/test_management.py
> Deploy system user assertion to device

- example.conf
- landscape/client/manager/config.py
- landscape/client/manager/snapmanager.py
- landscape/client/manager/snapservicesmanager.py
- landscape/client/manager/tests/test_config.py
- landscape/client/manager/tests/test_snapmanager.py
- landscape/client/manager/tests/test_snapservicesmanager.py
- landscape/client/manager/usermanager.py
- landscape/client/monitor/config.py
- landscape/client/monitor/snapmonitor.py
- landscape/client/monitor/snapservicesmonitor.py
- landscape/client/monitor/tests/test_snapmonitor.py
- landscape/client/monitor/tests/test_snapservicesmonitor.py
- landscape/message_schemas/server_bound.py
- snap/hooks/default-configure
~Makes sure the extra `services` field doesn't trip up the server after the next landscape server release~
> refactor: move snap services to separate manager & monitor

- landscape/lib/format.py
- landscape/lib/tests/test_format.py
The previous shell expansion left us vulnerable to code injection attacks. This change should address that.
> fix(expandvars): replace bash shell expansion with custom routine

- snap/snapcraft.yaml
When running `make snap-debug`, we're getting the following error:
```
:: dpkg-checkbuilddeps: error: Unmet build dependencies: python3-pycurl python3-netifaces python3-yaml ubuntu-advantage-tools locales-all python3-dbus
:: dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
:: dpkg-buildpackage: warning: (Use -d flag to override.)
```
Likely due to the extra dependencies added here:
```
Build-Depends: debhelper (>= 11), po-debconf, libdistro-info-perl,
dh-python, python3-dev, python3-distutils-extra,
lsb-release, gawk, net-tools,
python3-apt, python3-twisted, python3-configobj,
python3-pycurl, python3-netifaces, python3-yaml,
ubuntu-advantage-tools, locales-all, python3-dbus
```
> fix: add missing build packages to the snap

- landscape/client/manager/tests/test_usermanager.py
- landscape/client/manager/usermanager.py
- snap/snapcraft.yaml
`UserManager` was defaulting to `/etc/passwd` when the class is initialized without any params.
> fix(UserManager): pick correct shadow file on Core

- snap/snapcraft.yaml
This PR should switch us over to using the `python` build plugin when building the snap to stop depending and being affected by changes on the `.deb` build process.
Make sure to run `snapcraft clean` before doing a manual test
> fix(build snap): switch to the python build plugin

- snap/snapcraft.yaml
This will allow us to kill and end processes through the snap.
The before & after:
> fix(ProcessKiller): add process-control interface to the snap

- landscape/client/configuration.py
- landscape/client/tests/test_configuration.py
When setting up with the snap, it displays the wrong command in the summary:
```
The landscape-config parameters to repeat this registration on another machine are:
sudo landscape-config --account-name [...]
```
It should now point to `landscape-client.config` instead:
```
The landscape config parameters to repeat this registration on another machine are:
sudo landscape-client.config --account-name [...]
```
> fix(setup): display correct landscape config command on snap

- landscape/client/broker/registration.py
- landscape/client/broker/tests/test_registration.py
A fix (#215) to incorrect Livepatch reporting unintentionally removed Ubuntu Pro info during registration.  This reverts that change.
> fix ubuntu pro info on registration

- snap/snapcraft.yaml
Added network-manager and network-control plugs to the snap. This is for the D'crypt edge case and will need to be manually connected. We do not have any plans to ask for auto-connection at this stage.
> Add network-manager and network-control plugs

- landscape/client/manager/tests/test_ubuntuproinfo.py
- landscape/client/manager/ubuntuproinfo.py
The snap cannot call the `pro` client to get Ubuntu Pro info, which occurs during registration.  We still need ubuntu_pro_info to be called during registration to provide mocked pro info for Core (i.e., Core snap) management.
https://bugs.launchpad.net/landscape-client/+bug/2059136
> Fix registration for snap

- snap/hooks/configure
- snap/hooks/default-configure
This will allow us to change the `landscape-client.conf` config file using snap set.
`snap set` doesn't allow us to view the previous value of the config so we have to clean up the snap config to detect changes on the next run. Unsetting the values helps us avoid conflicts with configuration written through `landscape-client.config`.
It also expands the range of options that can be set. For instance, it's now possible to configure the plugins when using a gadget snap.
Please note that the landscape-client service needs to be restarted after config changes.
Issue reported by @dilyn-corner
> allow changing the landscape snap config using snap set

- debian/landscape-sysinfo.wrapper
Incorrect reference to the `CORES` variable meant that `THRESHOLD` was always `1.0`. Not entirely fatal to the sysinfo script, but does significantly change the odds whether the system is deemed to have too high a load to collect sysinfo.
> d/landscape-sysinfo.wrapper fix case on CORES variable

- Makefile
- README
The snap version for the `snap-install` & `snap-clean` make targets is fixed to `0.1`. This change will ensure that it changes dynamically as the `snapcraft.yaml` file evolves.
Developers are required to install [yq](https://github.com/mikefarah/yq) on their machine.
> chore(snap make targets): remove hardcoded snap version

- landscape/lib/apt/package/facade.py
- landscape/lib/apt/package/testing.py
- landscape/lib/apt/package/tests/test_facade.py
See https://bugs.launchpad.net/landscape-client/+bug/2062561 for more context.
The dependency used to collect APT source info, `aptsources`, added support for deb822-formatted `.sources` files, but this support is "opt-in" via a flag passed to the `SourceList` during instantiation.
This kwarg flag doesn't exist in older versions, so using it directly would break on jammy (and earlier), so this change instead sets the attribute after instantiation and re-collects the sources if it does.
Please manually run the tests on noble daily, as we don't have a github runner to do so yet.
> include deb822 sources when collecting source channels (LP: #2062561)

- .gitmodules
Noticed that `snap-http` was moved to https://github.com/canonical/snap-http hence the update.
`checkout` on CI okay:
> chore: update remote for snap-http submodule

- landscape/lib/network.py
- landscape/lib/tests/test_network.py
Currently not all interfaces show up in the API response (interfaces with no IP address, in the down state, etc...). 
This patch makes any interface that is not filtered out and has a valid MAC address show up in the API response. All previously included interfaces will still show up as expected.
Mainly interfaces in the down state as well as interfaces in the up state but with no IP address assigned to them will now show up in the API response as long as they have a MAC address. 
The IP address, broadcast address and net-mask for these interfaces will be set to `0.0.0.0`.
> Add non-filtered interfaces to the API response (LP: #2052834)

- landscape/client/broker/tests/test_transport.py
https://bugs.launchpad.net/landscape-client/+bug/2068050
The version of pycurl/curl in oracular emits a different error string when self-signed cert validation fails. This causes this test to fail.
> fix: allow for oracular version of pycurl error string (LP: 2068050)

- landscape/client/configuration.py
We should use `example.com` for such examples.
> Change FQDN example

- .gitignore
- landscape/client/deployment.py
- landscape/client/tests/test_deployment.py
- landscape/client/tests/test_watchdog.py
- landscape/client/watchdog.py
This is a fix for an issue reported [here](https://forum.snapcraft.io/t/reboot-required-before-landscape-client-device-available-in-backend/41069).
When building a gadget snap and we configure auto-setting the computer title, it's not set until the landscape-client service is restarted. This occurs when we're waiting for the device's serial.
Given the following config in the `gadget.yaml`:
```yaml
defaults:
ffnH0sJpX3NFAclH777M8BdXIWpo93af:
landscape-url: "https://landscape.stephenmwangi.com"
account-name: "standalone"
registration-key: "RegKey"
log-level: debug
auto-register:
enabled: true
computer-title-pattern: ${serial}
wait-for-serial-as: true
```
<details>
<summary>Logs after starting the Ubuntu Core device - the process gets stuck here <i>(click collapsible)</i></summary>
``` …
```
> fix: retry setting the computer title

- .github/workflows/ci.yml
- landscape/client/deployment.py
Got feedback [here](https://forum.snapcraft.io/t/reboot-required-before-landscape-client-device-available-in-backend/41069/11) to reduce the delay between retries. The initial 2 minutes was a little too long.. Now we'll retry after 15s, then 30, 60, etc over a span of ~30 minutes.
> fix: reduce computer title retry delay

- landscape/client/__init__.py
- landscape/client/manager/tests/test_ubuntuproinfo.py
- landscape/client/manager/ubuntuproinfo.py
- snap/snapcraft.yaml
[The Bug Report](https://bugs.launchpad.net/landscape-client/+bug/2074026)
This fix will allow the snap to push Ubuntu Pro information to Landscape by reading the `/var/lib/ubuntu-advantage/status.json` file. We have a `system-files` plug for this file.
One caveat is that the `data_dir` setting (`/var/lib/ubuntu-advantage/`) can be changed in `/etc/ubuntu-advantage/uaclient.conf` which would prevent the snap from reading the status file, as we can't plug into arbitrary folders on the host fs, especially not at runtime.
<details>
<summary>Sample Output (click to expand)</summary>
</details>
> fix: get ubuntu pro info on snaps

- .dev-lxc/config.yaml
The configuration of the container for Landscape client would use `dev-lxc` to set up the container, but would then require the user to run a few more manual steps. Here, those additional manual steps are now done automatically. The command should be run as:
```
dev_lxc create --config ./.dev-lxc/config.yaml jammy
```
> build: use dev-lxc to fully configure container

- landscape/client/package/tests/test_reporter.py
apt-cache expects all package repositories to have the `Date` field and some kind of hash (`MD5Sum`, `SHA1`, `SHA256`) field in their `Release` files. It will emit a warning it either of these are missing, which was polluting our test output. This patch adds these fields in tests to satisfy apt-cache.
> fix: add Date and hash fields to tests that create repositories

- landscape/lib/apt/package/facade.py
Ubuntu 24.04 and higher expect the `preferences.d` directory to exist in any directory being treated as an APT config directory. Creation of this directory was missing in `AptFacade`, which was leading to warnings when running some tests, such as `andscape.lib.apt.package.tests.test_facade.AptFacadeTest.test_custom_root_create_required_files`.
> fix: ensure preferences.d directory exists in created APT dirs

- Makefile
- landscape/lib/run_tests.py
Twisted Trial has a bug where the `_AdaptedReporter` is missing the `addDuration` method. A warning is emitted for this in Python 3.12. This patch adds a no-op one to eliminate these warnings. It can be removed once this is fixed in Twisted.
> fix: patch missing Trial addDuration method in py312

- debian/landscape-client.postinst
- landscape/client/broker/service.py
- landscape/client/configuration.py
- landscape/client/deployment.py
- landscape/client/manager/keystonetoken.py
- landscape/client/manager/plugin.py
- landscape/client/manager/scriptexecution.py
- landscape/client/manager/snapmanager.py
- landscape/client/tests/test_configuration.py
- landscape/client/watchdog.py
- landscape/lib/persist.py
- landscape/lib/tests/test_persist.py
This addresses an issue where setting `umask 027` would not allow for registration.
> fix: ensure landscape homedir and broker.bpickle are owned by landscape (LP: #2065879)

- landscape-client.conf
- landscape/client/broker/config.py
- landscape/client/configuration.py
- landscape/client/deployment.py
- landscape/client/manager/config.py
- landscape/client/monitor/config.py
- landscape/client/package/reporter.py
- landscape/client/tests/test_deployment.py
- landscape/client/watchdog.py
- landscape/lib/cli.py
- landscape/lib/config.py
- landscape/lib/fetch.py
- landscape/lib/logging.py
- landscape/lib/tests/test_config.py
- landscape/sysinfo/deployment.py
- man/landscape-config.1
- man/landscape-config.txt
Refactor optparse to argparse. Should be mostly a drop-in replacement except for positional arguments (which were previously ignored). 
https://bugs.launchpad.net/landscape-client/+bug/2077360
To create similar functionality for `--manage-sources-list-d` as described in the report, landscape-config will parse the terminal command with an optional argument for t/f values.
> fix: add manage-sources-list-d CLI option (LP:2077360) ; refactor: optparse to argparse for CLI options

- debian/rules
- landscape/client/__init__.py
- landscape/client/manager/scriptexecution.py
- landscape/client/manager/tests/test_customgraph.py
- landscape/client/package/tests/test_changer.py
- landscape/client/package/tests/test_releaseupgrader.py
- landscape/client/tests/test_configuration.py
- landscape/client/tests/test_watchdog.py
- landscape/lib/tests/test_network.py
Some recent changes caused the tests to fail in a package building environment where there is no landscape user. These changes allow setting environment variables to configure the user that runs in a build environment.
> fix: tests pass in a build environment

- landscape/client/manager/livepatch.py
- landscape/client/manager/tests/test_livepatch.py
The LivePatch plugin runs `canonical-livepatch status --format humane` to get kernel information. 
```
$ canonical-livepatch status --format humane
last check: 54 minutes ago
kernel: 6.8.0-40.40-generic
server check-in: succeeded
kernel state: ✓ kernel series 6.8 is covered by Livepatch
patch state: ✓ no livepatches available for kernel 6.8.0-40.40-generic
tier: updates (Free usage; This machine beta tests new patches.)
machine id: asdfsasdfasdfasdf
```
However, if this command fails, we could not parse that output to still receive other information, and would result in a yaml parser error.
```
$ canonical-livepatch status --format humane
last check: 50 minutes ago
kernel: 6.8.0-41.41-generic
server check-in: failed: livepatch check failed: POST request to …
```
> fix: parse livepatch process status check

- snap/snapcraft.yaml
Added a content interface to snapcraft.yaml to allow another snap to access the annotations directory.
> Add annotations content interface to snapcraft.yaml

- landscape/client/monitor/packagemonitor.py
- landscape/client/package/reporter.py
- landscape/client/package/tests/test_reporter.py
- landscape/lib/apt/package/tests/test_skeleton.py
The fix was implemented in the `python3-apt` package. The changes in `landscape-client` now cause issues with package reporter on machines with certain locale configurations.
> fix: revert fix for (LP: #1827857)

- landscape/client/configuration.py
- landscape/client/registration.py
Verify that prior to this commit, `landscape-config` will fail if a self-signed cert is required and present in the config.
Try setting `ssl_public_key` in `client.conf` and calling `landscape-config --silent`
The remove `ssl_public_key` from `client.conf` and try calling `landscape-config --silent --ssl-public-key /path/to/your.pem`
In both cases, the connection will fail because of certificate verification failure.
Repeat the same two calls above and verify the registration message sends successfully.
> fix: landscape-config uses ssl_public_key if provided

- snap/snapcraft.yaml
After the [landscape-config refactor](https://github.com/canonical/landscape-client/pull/262/files), registering on new revisions of the snap fails since the `config` app cannot read files in `/sys/bus/xen/devices` & `/sys/class/dmi/id`.
To reproduce:
- `snap install landscape-client --edge`
- `sudo landscape-client.config ...` fails with the following error:
```
Traceback (most recent call last):
File "/snap/landscape-client/294/usr/bin/landscape-config", line 16, in <module>
main(sys.argv[1:])
File "/snap/landscape-client/294/usr/lib/python3.10/site-packages/landscape/client/configuration.py", line 914, in main
exit_code = attempt_registration(identity, config)
File "/snap/landscape-client/294/usr/lib/python3.10/site-packages/landscape/client/configuration.py", line 739, in …
```
> fix: registration with landscape-client.config on the snap

- landscape/client/broker/tests/test_transport.py
- landscape/client/broker/transport.py
- landscape/client/exchange.py
- landscape/client/tests/test_exchange.py
- landscape/client/tests/test_registration.py
After [this change](https://github.com/canonical/landscape-client/pull/262), we're not fully processing the server's response leading to some weird behavior... like the client & server getting stuck since the client is not providing the expected `exchange-token` or `sequence`. And we end up not processing any messages _hours_ after registration:
This behavior can be seen with the latest snap revisions from the `edge` channel (probably all revisions after revision 244).
Cause
---
Server responses look like:
```
{'client-accepted-types-hash': b'N\x82(WO\x9a\x11}E\xda\x91\xbb\xcf\xc6\\.',
'messages': [],
'next-exchange-token': b'3274f7dd-3e6a-4cfd-ae66-a43ed5845e42',
'next-expected-sequence': 53,
'server-api': '3.3',
'server-uuid': b'f1a65772-c771-11ea-927a-0017a48f36ae'}
```
yet, the …
> fix: process full server response

- debian/control
python3-yaml is required for snap management when parsing snap assertions. Without it, the landscape-client service fails to start. It's often already installed in Ubuntu installations, so sometimes it works without being an explicit dependency.
This change ensures that it is an installed dependency.
> fix: add missing python3-yaml to runtime dependencies (LP: #2084586)

- snap/hooks/configure
- snap/hooks/post-refresh
- snap/snapcraft.yaml
Reverting to a previous snap revision leads to duplicate machine entries because the snap's data is stored in `$SNAP_DATA` and not `$SNAP_COMMON`. When the data is stored in `$SNAP_DATA`, the snap starts seeing the old data from the previous revision of the snap. Since the state (message id, etc) doesn't match the one tracked by the server, a re-registration is requested leading to clones.
The full bug report is available on [Launchpad](https://bugs.launchpad.net/landscape-client/+bug/2082616).
How to reproduce
---
1. Install landscape-client from the `stable` channel & register:
```console
$ snap install landscape-client
$ snap set landscape-client log-level="debug"
$ snap set landscape-client exchange-interval=300
$ sudo landscape-client.config ...
[...]
Registration request sent …
```
> fix: prevent creation of clones after reverting to previous snap revision

- landscape/client/configuration.py
- landscape/client/registration.py
- landscape/client/tests/test_configuration.py
- Follow instructions [here](https://ubuntu.com/landscape/docs/install-landscape-client#heading--install-landscape-client-from-a-PPA) to install client and use `ppa:landscape/self-hosted-beta`
- Connect client to ppa beta version of self hosted server following instructions [here](https://ubuntu.com/landscape/docs/quickstart-deployment)
- After connecting client wait a few minutes and client should go offline as it is not pinging the server
- Use this version of client
- Connect client to self hosted server
- Verify ping is working and connection doesn't go offline
> Fix: insecure id not set during registration on self hosted

- landscape/client/broker/registration.py
- landscape/client/configuration.py
- landscape/client/tests/test_configuration.py
- man/landscape-config.txt
- Register a new client to a server, without accepting the new computer on the server side yet
- Run `landscape-config --is-registered`, verify output says True
**_NOTE:_**  In order to not disrupt any workflows we added new command line arguments rather than editing existing ones
- Repeat registration without accepting step
- Run `landscape-config --actively-registered` and verify output is false
- Run `landscape-config --registration-sent` and verify output is true
- Accept the new computer on server end, and rerun `landscape-config --actively-registered`, verify output is True
> fix: fixed issues where --is-registered would print incorrect outputs

- landscape/client/deployment.py
- landscape/client/tests/test_deployment.py
- landscape/client/tests/test_watchdog.py
- landscape/client/watchdog.py
- Run new testcases provided (current branch) checking for when false parameter is sent in using old watchdog file
- Test cases will fail as Manager daemon is not spawned
- Run same testcases as above using new watchdog
- See that Manager daemon is spawned in cases where false is sent as parameter
> Fix: monitor-only not being set properly when false/no passed in config

- landscape/lib/fetch.py
- landscape/lib/tests/test_fetch.py
- Download landscape client and place self signed server certificate in an unreadable directory by landscape
- Try to connect client to server using the following command
`landscape-config --account standalone --url https://<server-ip>/message-system --ping-url https://server-ip/ping -k ssl-cert-location `
- Code should fail and provide no information as to why it fails
- Repeat above steps but instead using this version
- Verify that warning message is provided by logs
> Fix: SSL Certificates not properly surfaced

- landscape/client/broker/tests/test_transport.py
- landscape/lib/testing.py
Twisted changed a little bit - it used to run `cleanFailure` on `Failure` instances in the `defer` code but no longer does in the version available in plucky (python3-twisted 24.10).
This change does `cleanFailure` in the `FakeReactor` we use for some tests. This allows tests that rely on catching and flushing `Failure`s to succeed.
> fix: get tests passing on plucky

- debian/changelog
- landscape/__init__.py
There was no changelog from 24.08+git6391 to 24.11, so this adds that. No other changes from the 24.12 release.
> release 24.12

- landscape/client/manager/aptsources.py
- landscape/client/manager/tests/test_aptsources.py
https://bugs.launchpad.net/landscape-client/+bug/2087852
In client container (on main brain):
```
cd /etc/apt/sources.list.d
sudo touch hello.list
sudo touch hello.sources
```
In server container: `./dev/advicedog`
Now connect the client container to the server container. 
Then, open another tab in the server container:
```
source ./dev/setup-api
lsapi create-repository-profile hello-world
lsapi associate-repository-profile --all-computers hello-world
```
Observe the client container. After having the repository profile applied, notice that `.list` files have `.save` appended, while `.sources` files do not.
```
ls /etc/apt/sources.list.d
```
Now, checkout my branch in the client container:
```
git fetch --all
git checkout lndeng-1985-repository-profile-not-acting-on-source-files
sudo …
```
> feat: add support for .sources when applying repository profiles

- landscape/lib/tests/test_sequenceranges.py
You can validate this fix pretty easily:
1. create a plucky LXD container:
```bash
dev_lxc create plucky --config ./.dev-lxc/config.yaml
```
3. run the tests:
```bash
make check
```
Without this change, they will fail with:
```
builtins.AttributeError: module 'unittest' has no attribute 'makeSuite'
```
With this change, they should all pass (or skip).
> fix: remove deprecated use of `unittest.makeSuite` to get tests passing on >=py312

- .github/workflows/cla-check.yaml
Compare with, e.g., this successful run of the same action in a different repo: https://github.com/canonical/landscape-documentation/actions/runs/14109971121/job/39525837115
> ci: check if CLA is signed on each PR

- landscape/client/manager/tests/test_usgmanager.py
- landscape/client/manager/usgmanager.py
- landscape/message_schemas/server_bound.py
Fairly minor patch to add the `run-id` and `operation-id` fields to the `usg-audit` message type, as they are required for landscape-server to properly associate the results with their origin.
> fix: add run-id and operation-id fields to usg-audit message

- landscape/client/manager/tests/test_usgmanager.py
- landscape/client/manager/usgmanager.py
Ensure that usg is enabled:
```sh
sudo pro attach
sudo apt update
sudo apt install ubuntu-advantage-tools
sudo pro enable usg
sudo apt install usg
```
Generate a tailoring file (will be used to generate the security profile in LS)
```sh
sudo usg generate-tailoring disa_stig .
```
connect LC to server and make sure the UsgManager plugin is enabled.
```
include_manager_plugins = UsgManager
```
execute a security profile on server
> fix: usgmanager should accept only the profile or the tailoring file

- landscape/client/manager/aptsources.py
- landscape/client/manager/tests/test_aptsources.py
https://bugs.launchpad.net/landscape-client/+bug/2087852
---
The reason this is only "for noble" is because it uses DEB822-style sources in `/etc/sources.list.d` instead of `sources.list` like jammy and previous. 
Register a Landscape Client noble instance to Landscape Server.
In the client's `/etc/apt/sources.list.d`:
```bash
touch hello.list hello.sources
```
Create a repository profile, and associate it with the client. The easiest way is through the UI. Wait for the activity to run and in the client's `sources.list.d`, you should see:
```
hello.list.save 
hello.sources.save 
ubuntu.sources.save 
landscape-<profile-name>.list
```
Now, delete the repository profile or disassociate it with the instance, and wait for the activity to run. Now, check on the client's `sources.list.d` You …
> fix: .list and .sources files are restored when a repository profile is disassociated from a noble (or later) instance

- landscape/client/package/reporter.py
- landscape/client/package/taskhandler.py
- landscape/client/package/tests/test_reporter.py
- landscape/lib/apt/package/facade.py
- landscape/lib/apt/package/tests/test_facade.py
This change adds a configuration option `ignore_package_sources` or `--ignore-package-sources` that can be used to ignore specific source parts in `/etc/apt/sources.list.d`.
To test, add this line to your client.conf (or root-client.conf):
```
ignore_package_sources = landscape-ubuntu-self-hosted-beta-jammy.list
```
don't use `jammy` unless you're on jammy.
Then add that repo: `sudo add-apt-repository ppa:landscape/self-hosted-beta`
and run your client
```
sudo ./scripts/landscape-client --config ./root-client.conf
```
wait for your client to finish reporting packages.
Check that packages from the ignored source do not show up when searching packages, e.g., `landscape-server`. For this client.
> feat: configurably exclude package sources

- landscape/client/broker/exchange.py
- landscape/client/broker/tests/test_exchange.py
https://warthogs.atlassian.net/browse/LNDENG-2247
---
Connect a client running this branch to Landscape Server and wait for a couple of minutes. Then, in the Client instance, check for the new log entry in `broker.log`:
```
#root@landscape-client-jammy:/tmp/landscape
cat broker.log | grep "Pending messages"
...
2025-05-27 19:35:07,203 INFO     [MainThread] Pending messages remaining after the last exchange: 1
```
> feat: log pending message count

- landscape/client/broker/exchange.py
- landscape/client/broker/server.py
- landscape/client/broker/tests/test_registration.py
- landscape/client/broker/tests/test_server.py
- landscape/client/broker/transport.py
- landscape/client/configuration.py
- landscape/client/manager/keystonetoken.py
- landscape/client/monitor/updatemanager.py
- landscape/client/package/changer.py
- landscape/client/package/tests/test_changer.py
- landscape/client/tests/helpers.py
- landscape/client/tests/subunit.py
- landscape/client/tests/test_configuration.py
- landscape/client/user/provider.py
- landscape/lib/apt/package/facade.py
- landscape/lib/apt/package/skeleton.py
- landscape/lib/apt/package/testing.py
- landscape/lib/base64.py
- landscape/lib/bpickle.py
- landscape/lib/compat.py
- landscape/lib/disk.py
- landscape/lib/network.py
- landscape/lib/persist.py
- landscape/lib/testing.py
- landscape/lib/tests/test_reactor.py
- landscape/lib/tests/test_sysstats.py
- landscape/lib/user.py
- landscape/sysinfo/tests/test_sysinfo.py
This PR removes some code that only exists to support compatibility for both Python2 and Python3 environments. As Python2 is no longer supported, this code is not needed.
Note: after these changes, code supporting Python2 still remains and should be considered for removal.
> refactor: delete `landscape/lib/compat.py`

- snap/snapcraft.yaml
After some discussion [on the forum](https://forum.snapcraft.io/t/installation-request-for-landscape-client-writable-system-files/47209), it's been decided that #272 should be reverted. Please see the discussion there.
The tl;dr is, `/writable` has far-reaching implications since it's [the rootfs](https://github.com/canonical/snapd/blob/75d252871e4217fe32126c9e857510951a9fc8a1/dirs/dirs.go#L157) Ubuntu Core 🙂.
> revert: added /writable system-files interface to for script access (#272)

- landscape/message_schemas/server_bound.py
`landscape-client` never sends this message type, and `landscape-server` has no handler for it.
> refactor: delete unused eucalyptus message schema

- landscape/message_schemas/server_bound.py
`landscape-client` does not send this message and `landscape-server` does not have a handler for it. In fact, `landscape-server` dropped the corresponding table from the resource database in patch 29.
> refactor: remove oboslete client-uptime message schema

- landscape/message_schemas/server_bound.py
These self-advertise as obsolete.
`landscape-server` has no handlers for these message types.
> refactor: remove obsolete register-* message schemas

- landscape/client/broker/client.py
- landscape/client/deployment.py
- landscape/client/manager/scriptexecution.py
- landscape/client/manager/service.py
- landscape/client/manager/tests/test_scriptexecution.py
Adding a configuration option to set the working directory for script execution improves the CIS hardening experience. There is a "noexec on /tmp" rule that Landscape typically violates by requiring executables (scripts) in `/tmp`.
Include the following in your `client.conf`:
```ini
script_tempdir = /var/custom-tempdir
manager_plugins = ScriptExecution
script_users = landscape,ALL
```
Set up your custom dir for script execution by the `landscape` user:
```sh
sudo mkdir -p /var/custom-tempdir
sudo chown landscape:landscape /var/custom-tempdir
sudo chmod 700 /var/custom-tempdir
```
Run the client:
```sh
sudo scripts/landscape-client -c landscape-client.conf
```
I used `inotify` to verify that the scripts and attachments appeared in my temp directory:
```sh
sudo apt install inotify-tools …
```
> feat: add --script-tempdir configuration

- Makefile
- debian/control
- landscape/lib/versioning.py
- setup.py
Remove distutils so we can update to Core24 base for the snap, which uses Python3.12 in which distutils are not supported.
> Remove dist-utils

- snap/snapcraft.yaml
Removing distutils broke the build of the Core22 snap. Core24 worked fine but these settings needed tweaking so that Core22 still builds nicely without distutils and we can have a common foundation for 22&24 moving forward.
> Add setuptools, remove setup and fix paths in Snapcraft.yaml

- .github/workflows/update-release-branches.yml
- .gitignore
- Makefile
- README
- snap/snapcraft.yaml.j2
As discussed, the `main` branch will now have a template `snapcraft.yaml` which will be used to generate different yaml files for the core24 & core22 snaps.
Sample CI runs on my fork:
Core 24:
- [CI run](https://github.com/st3v3nmw/landscape-client/actions/runs/16889324813/job/47844834477)
- [Generated snapcraft.yaml](https://github.com/st3v3nmw/landscape-client/blob/core-24/snap/snapcraft.yaml)
Core 22:
- [CI run](https://github.com/st3v3nmw/landscape-client/actions/runs/16889324813/job/47844834494)
- [Generated snapcraft.yaml](https://github.com/st3v3nmw/landscape-client/blob/core-22/snap/snapcraft.yaml)
---
To create the commit, a git user is required but the `checkout` action [1] doesn't set the user so we have to set it up manually. We're attributing the commit to whoever triggered …
> build: create release tracks for core-22 & core-24

- .github/workflows/update-release-branches.yml
- README
- snap/snapcraft.yaml.j2
This PR is a follow-up on #352, it:
- Updates the commit message from `Update snapcraft.yaml` to `chore: update snapcraft.yaml`
- Adds a comment to `snap/snapcraft.yaml.j2` with instructions on how to generate the actual `snapcraft.yaml`
- Changes all codeblocks in the README to use `shell` for consistency... I picked `shell` over `console` because none of the examples show any output
> chore: update release job's commit message & clean up readme

- landscape/lib/uaclient.py
- Override `/landscape/client/__init__.py` and set `IS_SNAP` or `IS_CORE` to True
- Open python shell
- `from landscape.lib.uaclient import get_pro_status`
- `get_pro_status` 
- Verify logs say uaclient library unavailable
> fix: uaclient wrapper with snap and core devices

- .github/workflows/static-analysis.yml
On jammy, `coverage` requires `coverage[toml]` to read the `pyproject.toml`. This extension isn't in the Ubuntu archive for jammy, so rather than work around layering it on top of the archive-provided dependencies, this change simply bumps the runner up to noble, where the extension is included.
> build: run TiCS static analysis on noble
